[build]
  functions = "netlify/functions"
  publish = "." # Укажите папку, содержащую ваш HTML, CSS и JS

[dev]
  port = 4001
  functionsPort = 8888
  autoOpenBrowser = false # Чтобы браузер не открывался автоматически

[functions]
  included_files = ["./node_modules/mongodb/**"] #  Укажите зависимости для функций
