[build]
  functions = "netlify/functions"
  publish = "." # Укажите папку, содержащую ваш HTML, CSS и JS
  node_version = "18"

[dev]
  port = 4001
  functionsPort = 8888
  autoOpenBrowser = false # Чтобы браузер не открывался автоматически
